// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlsj9_LhUww1QfxKEohFhMWMzTb6_I7g',
    appId: '1:588223923280:web:bd2b537de92160bfa83d55',
    messagingSenderId: '588223923280',
    projectId: 'fir-2-94902',
    authDomain: 'fir-2-94902.firebaseapp.com',
    storageBucket: 'fir-2-94902.appspot.com',
    measurementId: 'G-JWEHZGNR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU4ztu6b3SmFwzsG55w3KSdivnbADczN4',
    appId: '1:588223923280:android:92f428a979e36714a83d55',
    messagingSenderId: '588223923280',
    projectId: 'fir-2-94902',
    storageBucket: 'fir-2-94902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6X1YG7jy-QKgqYr-4OSwqiZzCaN0-gv4',
    appId: '1:588223923280:ios:5acb14a7ae94bae2a83d55',
    messagingSenderId: '588223923280',
    projectId: 'fir-2-94902',
    storageBucket: 'fir-2-94902.appspot.com',
    iosBundleId: 'com.example.firebaseTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6X1YG7jy-QKgqYr-4OSwqiZzCaN0-gv4',
    appId: '1:588223923280:ios:5acb14a7ae94bae2a83d55',
    messagingSenderId: '588223923280',
    projectId: 'fir-2-94902',
    storageBucket: 'fir-2-94902.appspot.com',
    iosBundleId: 'com.example.firebaseTut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlsj9_LhUww1QfxKEohFhMWMzTb6_I7g',
    appId: '1:588223923280:web:249654277872d62ea83d55',
    messagingSenderId: '588223923280',
    projectId: 'fir-2-94902',
    authDomain: 'fir-2-94902.firebaseapp.com',
    storageBucket: 'fir-2-94902.appspot.com',
    measurementId: 'G-00PHMTNL8R',
  );
}
